# FASE 6: Ruta para servir archivos estáticos (fotos de pacientes)
# He unificado la propiedad a 'app.uploads.pacientes.path' para que coincida con WebMvcConfig.
# La propiedad 'app.upload.pacientes-dir' y 'spring.web.resources.static-locations' han sido eliminadas para evitar duplicidad.
# ========================================================
# Si quieres probar en tu PC local:
spring.datasource.url=jdbc:mysql://localhost:3306/veterinaria_mejia_final
spring.datasource.username=root
spring.datasource.password=


# ========================================================
# 2. CONFIGURACIÓN DE JPA / HIBERNATE
# ========================================================
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ========================================================

# Resto de tus configuraciones...
# ========================================================
spring.thymeleaf.cache=false
server.servlet.session.timeout=30m

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB

app.uploads.pacientes.path=${user.home}/vetmejia-uploads/pacientes/

# ========================================================
# 7. FACTURACIÓN ELECTRÓNICA — NUBEFACT (PSE)
# ========================================================
# MODO DEMO (prueba sin envío a SUNAT):
nubefact.modo.prueba=true

# TOKEN de la empresa (Obtenlo en tu panel de NubeFact > Configuración > API):
nubefact.api.token=32f107952ede490fae2d9d987574c3181f370945683c4118a95476537e5a7e4f

# URL base de la API Nubefact (Copia la URL exacta que te da tu panel de NubeFact en Configuración > API):
nubefact.api.url=https://api.nubefact.com/api/v1/187196bb-a7bb-4ae1-86f7-a92e8c58b2c9

# Datos de la empresa emisora que registraste en tu entorno de pruebas:
nubefact.ruc=10736710515
nubefact.razon.social=Veterinaria Mejia1

server.forward-headers-strategy=framework
# PARA PRODUCCION: cambiar modo.prueba=false y ingresar token real

# ── SCHEDULING (contingencia SUNAT C5) ─────────────────────────────────────
spring.task.scheduling.pool.size=2

# ── SPRINGDOC OPENAPI (M3) ──────────────────────────────────────────────────
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

# ── CACHE Caffeine (M4) ─────────────────────────────────────────────────────
spring.cache.type=caffeine

# ── VALIDACIÓN RUC / SUNAT (A1) ─────────────────────────────────────────────
# Endpoint para buscar personas naturales
sunat.api.dni.url=https://api.apis.net.pe/v2/reniec/dni

# Endpoint para buscar empresas
sunat.api.ruc.url=https://api.apis.net.pe/v2/sunat/ruc

# Token de autorización (Bearer) para consumir la API de apis.net.pe
sunat.api.token=sk_16846.as5Nh78qkIjU5rubzITjNHbfNzpAWXKz
